
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/hn_tes?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
#    username: root
#    password: root


    url: jdbc:mysql://47.93.189.30:3306/hn_tes?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
    username: hn_tes
    password: bugu2019!@#$%
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


hn:
  tes:
#  自动封场推迟几分钟，考试时间结束后自动封场
    auto-close-scene-delay: 3
server:
  servlet:
    context-path: /hn

bugu:
  init:
    password: 888888


