
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hn_tes?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: betaHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1

#    url: jdbc:mysql://47.93.189.30:3306/hn_tes?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
#    username: hn_tes
#    password: bugu2019!@#$%
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml


hn:
  tes:
#  自动封场推迟几分钟，考试时间结束后自动封场
    auto-close-scene-delay: 3
server:
  servlet:
    context-path: /hn
  port: 10000

bugu:
  init:
    password: 888888

